CDAC-Final-Project-KD-J024/InsureEase

insure-ease-frontend/src/slices/authSlice.js
Implemented Redux Auth Slice with User Authentication & Profile Management
=> authSlice feature implemented

insure-ease-frontend/src/store/store.js
Updated Redux Store Configuration with Centralized State Management
=> store status modified

insure-ease-frontend/src/slices/claimSlice.js
Claim Slice Feature implemented
=> claim slice feature added

insure-ease-frontend/src/slices/orderSlice.js
=> Order slice feature added

insure-ease-frontend/src/slices/adminSlice.js
admin slice feature implemented
=> admin slice implemented

insure-ease-frontend/src/slices/policySlice.js
Policy slice implemented and 5 reducer functions are also added
=> policy slice intiated and implemented 5 reducer functions as well

insure-ease-frontend/src/slices/policySlice.js
=> policy slice feature added

insure-ease-frontend/src/slices/userPolicySlice.js
user policy feature added with 4 reducers
=> user policy feature added with 4 reducers functions

insure-ease-frontend/src/slices/userPolicySlice.js
Added four functions in this slice
=> user policy slice modified

insure-ease-frontend/src/App.jsx
App.jsx page created and all the routes are defined
=> App.jsx page created

insure-ease-frontend/src/components/admin/AddPolicy.jsx
AddPolicy.jsx created and completed
=> add policy page added

insure-ease-frontend/src/components/admin/EditPolicy.jsx
=> EditPolicy.jsx implemented

insure-ease-frontend/src/components/admin/OrderDetails.jsx
OrderDetails.jsx page implemented
=> order details page added

insure-ease-frontend/src/App.jsx, insure-ease-frontend/src/components/admin/PolicyDetailsAdmin.jsx
PolicyDeailsAdmin page created
=> policy details admin page created

insure-ease-frontend/src/components/admin/UserDetails.jsx
=> user details page created

insure-ease-frontend/src/components/common/ProtectedRoute.jsx
=> protected route

insure-ease-frontend/src/pages/admin/AdminDashboard.jsx
=> Admin dashboard creatred

insure-ease-frontend/src/pages/admin/ApproveClaims.jsx, insure-ease-frontend/src/pages/admin/ManageOrders.jsx
=> ManageOrders Page Created

insure-ease-frontend/src/pages/admin/ManageUsers.jsx
=> ManageUsers Page Created

insure-ease-frontend/src/pages/common/CarInsurance.jsx
=> CarInsurance Page Created

insure-ease-frontend/src/pages/common/CarInsuranceCalculator.jsx
CarInsuranceCalculator Page Created
=> CarInsuranceCalculator Page Created

insure-ease-frontend/src/pages/common/LifeInsurance.jsx
=> LifeInsurance.jsx page created

insure-ease-frontend/src/pages/common/LifeInsuranceCalculator.jsx
Life Insurance Calculator page created
=> Life Insurance Calculator page created

insure-ease-frontend/src/pages/common/Login.jsx
=> Login page created

insure-ease-frontend/src/pages/common/HealthInsuranceCalculator.jsx
Health insurance calculator feature added
=> health insurance calculator added

insure-ease-frontend/src/pages/common/Register.jsx
Register page created successfully
=> Register.jsx created

insure-ease-frontend/src/pages/user/ClaimStatus.jsx
Claim status page created and upload
ed
=> Claim status created

insure-ease-frontend/src/pages/user/Dashboard.jsx
Dashboard.jsx created successfully
=> Dashboard.jsx created

insure-ease-frontend/src/pages/user/MyPolicies.jsx
=> My Policies page created

insure-ease-frontend/src/pages/user/Orders.jsx
Orders.jsx created successfully
=> Orders.jsx created

insure-ease-frontend/src/pages/user/PolicyDetails.jsx
=> Policy details created successfully

insure-ease-frontend/src/pages/user/Profile.jsx
Profile.jsx created successfully
=> Profile.jsx created successfully

insure-ease-frontend/src/App.jsx, insure-ease-frontend/src/components/admin/AddPolicy.jsx, insure-ease-frontend/src/components/admin/EditPolicy.jsx, insure-ease-frontend/src/components/admin/OrderDetails.jsx, insure-ease-frontend/src/components/admin/PolicyDetailsAdmin.jsx, insure-ease-frontend/src/components/admin/UserDetails.jsx, insure-ease-frontend/src/pages/admin/ApproveClaims.jsx, insure-ease-frontend/src/pages/admin/ManageOrders.jsx, insure-ease-frontend/src/pages/admin/ManagePolicies.jsx, insure-ease-frontend/src/pages/admin/ManageUsers.jsx, insure-ease-frontend/src/pages/common/Home.jsx, insure-ease-frontend/src/pages/user/Claims.jsx, insure-ease-frontend/src/pages/user/Dashboard.jsx, insure-ease-frontend/src/slices/authSlice.js, insure-ease-frontend/src/slices/policySlice.js, insure-ease-frontend/src/store/store.js
All the errors resolved of the UI
=> all the ui errors resolved
